<a href="https://colab.research.google.com/github/aziza-orifjonova/pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'e', 'g'])
s1

a    1
b    2
c    3
e    4
g    5
dtype: int64

In [3]:
s2 = pd.Series([6, 7, 8, 9, 10], index=['a', 'c', 'd', 'e', 'h'])
s2

a     6
c     7
d     8
e     9
h    10
dtype: int64

In [4]:
s1+s2     #Series'da ikkovida index bor bo'lishi kk

a     7.0
b     NaN
c    10.0
d     NaN
e    13.0
g     NaN
h     NaN
dtype: float64

In [6]:
d1 = pd.DataFrame(np.arange(9.).reshape(3, 3), columns=list('abc'), index=['Anor', 'Banan', 'Do\'lana'])
d1

           a    b    c
Anor     0.0  1.0  2.0
Banan    3.0  4.0  5.0
Do'lana  6.0  7.0  8.0

In [14]:
d2 = pd.DataFrame(np.arange(12.).reshape(4, 3), columns=list('bcd'), index=['Kivi', 'Anor', 'Banan', 'Nok'])
d2

         b     c     d
Kivi   0.0   1.0   2.0
Anor   3.0   4.0   5.0
Banan  6.0   7.0   8.0
Nok    9.0  10.0  11.0

In [15]:
d1+d2           #DataFrame'da index va column ikkovida bor bo'lishi kk

          a     b     c   d
Anor    NaN   4.0   6.0 NaN
Banan   NaN  10.0  12.0 NaN
Do'lana NaN   NaN   NaN NaN
Kivi    NaN   NaN   NaN NaN
Nok     NaN   NaN   NaN NaN

In [18]:
d1.add(d2, fill_value=1)        #fill value ikkovidan birida bor, index ham-column ham va value + x{fill_value}

           a     b     c     d
Anor     1.0   4.0   6.0   6.0
Banan    4.0  10.0  12.0   9.0
Do'lana  7.0   8.0   9.0   NaN
Kivi     NaN   1.0   2.0   3.0
Nok      NaN  10.0  11.0  12.0